### ISSUE TITLE
BAFANG M400 "Controller does not have available to read and write parameter pack"

### ISSUE THREAD

**Issue by igolisck** [andrey-pr/OpenBafangTool#10]
Hi,

when I connect to my Bafang M400 I can not address Motor values and see the following error.

![image](https://github.com/andrey-pr/OpenBafangTool/assets/157604242/ffaa32d9-295c-44e4-89b1-ff6496e888eb)

Thank you

**Comment by andrey-pr** [comment]
Hello. Are all other values available? If yes, it works as should: some of motors just have firmware with limited commands, without parameter packs #1 and #2. I warned about this in readme
