### ISSUE TITLE
Walk mode modifying

### ISSUE THREAD

**Issue by shikhov** [andrey-pr/OpenBafangTool#11]
Is it possible to change the power of walk mode? My firmware has extremely weak walk mode :(

**Comment by andrey-pr** [comment]
Do you want to change walk assist speed or max current?

**Comment by shikhov** [comment]
Hmm... good question. Both :)

**Comment by andrey-pr** [comment]
> Hmm... good question. Both :)

Its technically possible to configure speed, but I don't remember if I already added this parameter to UI, I should check out. If no, will add in next release

**Comment by andrey-pr** [comment]
Well, this parameter is not available in UI yet. Will add in next release

**Comment by andrey-pr** [comment]
@shikhov added walk assist speed parameter to source code. It will be available in next release
