### ISSUE TITLE
Question: Torque Sensor

### ISSUE THREAD

**Issue by dborren** [andrey-pr/OpenBafangTool#20]
Thank you for your continued support on this amazing tool! I have a question regarding my BB Torque sensor. I recently installed a original Bafang Torque sensor BB on my bicycle (PA211.32.ST). I would like to have the controller recognize the sensor. Right now it feels like it is just functioning as a cadence sensor. Would you happen to know the correct settings for my BB sensor? Or is it not supported at the moment?

Thank you and kind regards,

Diederik

**Comment by andrey-pr** [comment]
Yes, there is switch called "trigger mode" or something like it, I don't remember actual name. It has three options - "cadence sensor and throttle lever", "torque sensor and throttle lever", "throttle lever only". You need to set it to "torque sensor and throttle lever"
