### ISSUE TITLE
can't see my usb can device

### ISSUE THREAD

**Issue by Ondras4260** [andrey-pr/OpenBafangTool#22]
hello, i have SPI-CAN chip + can transiever, now i have the SPI-CAN board connected to arduino on Serial COM6 and i read all the can communication on my bafang M400 just fine, is there some special thing i have to do so that the Open Bafang Tool can see the arduino and communicate ?

![image](https://github.com/user-attachments/assets/7539d0b6-e137-40dd-97df-58b234f1af13)
 
![image](https://github.com/user-attachments/assets/16243c00-7fa2-437e-87fd-a605d492c6da)

![image](https://github.com/user-attachments/assets/1bfa9651-8b15-4055-9a86-7eafacea6db0)

**Comment by andrey-pr** [comment]
You need original besst tool. Your device have incompatible protocol
