### ISSUE TITLE
Moteur m500

### ISSUE THREAD

**Issue by Patrice2922** [andrey-pr/OpenBafangTool#24]
Bonjour 
Je viens d'acheter un vélo avec un moteur bafang m500, je souhaiterai modifier les paramètres. 
Est ce que je peux utiliser le logiciel open source et juste le connecteur canbus display connector ?
Merci pour votre réponse et pour votre travail.

**Comment by andrey-pr** [comment]
Do you speak English or German?

**Comment by Patrice2922** [comment]
English
 
Patrice CARADEC
Opticien basse vision à domicile
4 rue Youenn Gwernig
29410 SAINT THEGONNEC
06 60 68 51 40
***@***.***
http://www.monopticienchezmoi.fr
----------------De : andrey-pr ***@***.***>Envoyé : mardi 29 octobre 2024 14:00À : andrey-pr/OpenBafangTool ***@***.***>Cc : Patrice2922 ***@***.***>; Author ***@***.***>Objet : Re: [andrey-pr/OpenBafangTool] Moteur m500 (Issue #24)
Do you speak English or German?

**Comment by Patrice2922** [comment]
Je suis français, j'utilise Google traduction pour vous parler. 
Pouvez-vous m'aider ?
Merci

**Comment by andrey-pr** [comment]
> Bonjour 
> Je viens d'acheter un vélo avec un moteur bafang m500, je souhaiterai modifier les paramètres. 
> Est ce que je peux utiliser le logiciel open source et juste le connecteur canbus display connector ?
> Merci pour votre réponse et pour votre travail. 

What kind of connector do you want to use? You need green connector on main cable and device called besst tool. You can not use usb charging port on display or any other connectors

**Comment by Patrice2922** [comment]
Hello, Can you give me the reference of a connector to connect it to my computer and use the software?
Thanks

**Comment by andrey-pr** [comment]
> 
> Hello, Can you give me the reference of a connector to connect it to my computer and use the software?
> Thanks

![de6ad255-71f3-48c7-8149-71d70a9e30b4.jpeg](https://github.com/user-attachments/assets/de52a49d-31c0-431e-9181-9964405e5e53)

If you want to work with CAN system, you need this device. It called "BESST Tool"
