### ISSUE TITLE
Incompatible Firmware

### ISSUE THREAD

**Issue by ShalokShalom** [andrey-pr/OpenBafangTool#5]
I am currently looking to buy an Ebike conversion kit.

It is important to me, that I find one with an open source tool to configure.

I was already about to buy a modern Bafang one, and just read the last minute on the forum, that some/most modern firmwares are not compatible.

I would have almost bought such a device, and strongly suggest to add a warning to the Github page.

**Comment by andrey-pr** [comment]
Hello. Yes, I will add warning. But these devices are not completely incompatible: some settings are not available, but other functions (diagnostics, wheel size setting, etc) are still available. What model did you plan to buy? Most of kits on Amazon still have uart controllers. Later I will search for solution of this problem with other bafang enthusiasts - theoretically problem could be solved by one reflash, I will contact people who have experience with changing firmwares

**Comment by ShalokShalom** [comment]
Wonderful! 

I have not decided yet, the Tongshen TSDG8 looks promising. 

I would love to buy a modern 820 or so on the aftermarket, while they seem OEM only.

Old Bafang sadly have no torque sensor.

**Comment by andrey-pr** [comment]
> Wonderful!
> 
> I have not decided yet, the Tongshen TSDG8 looks promising.
> 
> I would love to buy a modern 820 or so on the aftermarket, while they seem OEM only.
> 
> Old Bafang sadly have no torque sensor.

Tonghshengs are absolutely not supported by this or any other project - I even don't think that they have configuration api at all.

Some of old bafangs have torque sensor, but they are designed for special frame, not for usual (as well as new). If you are enthusiast is bike building, there is also possibility to build bike from old usual ebike with dead motor and new bafang electrics - Tomblarom produces and sells special hardware kits to install new bafang mid-drive on frame designed for bosch, or shimano, or yamaha (disclaimer: I don't know details about this technology. Contact him directly to know more).

Also, there is https://github.com/OpenSourceEBike/Bafang_M500_M600 project, collaborated with GreenBikeKit shop - I think they can offer you some good solution

**Comment by ShalokShalom** [comment]
> Tonghshengs are absolutely not supported by this or any other project - I even don't think that they have configuration api at all.

There is custom firmware for the TSDG2(B) that supports way more configuration options than this project. 

But it requires a special cable, voids the warranty, and the engine requires a custom cooling solution for higher speeds, which costs time and work on top. 

The 8 has no tooling yet, and is better across all aspects, except the weight. 

https://github.com/emmebrusa/TSDZ2-Smart-EBike-1

> 
> Also, there is https://github.com/OpenSourceEBike/Bafang_M500_M600 project, collaborated with GreenBikeKit shop - I think they can offer you some good solution

I know that project. I just dont know, where I can get engines for it. Buying a broken bike seems suboptimal. I like to buy the engine from some shop.

**Comment by andrey-pr** [comment]
> > Tonghshengs are absolutely not supported by this or any other project - I even don't think that they have configuration api at all.
> 
> There is custom firmware for the TSDG2(B) that supports way more configuration options than this project.
> 
> But it requires a special cable, voids the warranty, and the engine requires a custom cooling solution basically.
> 
> Which costs time and work on top.
> 
> The TSDG8 has no tooling yet, and is better across all aspects than the older sibling, except the weight.
> 
> https://github.com/emmebrusa/TSDZ2-Smart-EBike-1
> 
> > Also, there is https://github.com/OpenSourceEBike/Bafang_M500_M600 project, collaborated with GreenBikeKit shop - I think they can offer you some good solution
> 
> I know that project. I just dont know, where I can get engines for it. Buying a broken bike seems suboptimal.
> 
> I like to buy the engine from some shop.

If your plan is to buy custom bike, you can buy engine and compatible frame from GreenBikeKit. If not, you can ask crew of this project for help to find firmware for your bafang device with available settings - not the reliablest way, but still more reliable than flash tongsheng with completely "homebrew" firmware

**Comment by ShalokShalom** [comment]
I am looking to build my own bike, and if there is a request, I would also build it for other people then. 

So I like a reliable way of "engine x works" and "I can get it there and here"

Also, the offerings from Varstrom are so cheap, its really difficult to justify buying somewhere else. 

And the only torque based devices there are again Tongshen. 

I would love a hardware mod for Bafang devices, that retrofits them with torque sensors. 

Or the way Geeko does it, by attaching a sensor to the cassette.

**Comment by andrey-pr** [comment]
Added info about supported hardware and possible firmware limitations
