### ISSUE TITLE
Support for hub motors

### ISSUE THREAD

**Issue by ShalokShalom** [andrey-pr/OpenBafangTool#6]
Does the software also support the hub motors from Bafang?

Documentation only lists mid motors, and it says "or any other"

I am especially asking for the H640 and [H400B](https://varstrom.com/products/bafang-500w-48v-rear-hub-cassette_1).

**Comment by andrey-pr** [comment]
Yes, if moyor has bafang controller. All kinds of controllers, manufactured by bafang are supported

**Comment by andrey-pr** [comment]
> Does the software also support the hub motors from Bafang?
> 
> Documentation only lists mid motors, and it says "or any other"
> 
> I am especially asking for the H640 and [H400B](https://varstrom.com/products/bafang-500w-48v-rear-hub-cassette_1). 

I don't know what kind of controller is inluded in this kit. If its bafang its supported, if some other brand no

**Comment by ShalokShalom** [comment]
Thanks a lot. Do you think it makes sense to note that in the README?
I would send a PR

**Comment by andrey-pr** [comment]
Added info about supported hardware and possible firmware limitations

**Comment by ShalokShalom** [comment]
> All kinds of modern bafang hardware with CAN bus are supported: all mid-drive motors, all hub motors with bafang controller, all displays and all digital torque sensors, as well as all kinds of motors with UART (but not displays with UART).

Well, thats great. But as far as I understand, is the suppport for e.g CAN motors strictly limited.

So saying they are supported, means to some users, they are capable of limiting and lifting the speed limit, adjusting the support level, and so on. 

Maybe a sheet, with detailed info on what is supported for what device (class) is helpful?

**Comment by andrey-pr** [comment]
> > All kinds of modern bafang hardware with CAN bus are supported: all mid-drive motors, all hub motors with bafang controller, all displays and all digital torque sensors, as well as all kinds of motors with UART (but not displays with UART).
> 
> Well, thats great. But as far as I understand, is the suppport for e.g CAN motors strictly limited.
> 
> So saying they are supported, means to some users, they are capable of limiting and lifting the speed limit, adjusting the support level, and so on. 
> 
> Maybe a sheet, with detailed info on what is supported for what device (class) is helpful?

```
Important notices:

Some devices have firmware with limited configurable parameters, and it does not depends on model. For example, I tested 3 absolutely same M420 mid-drives, and two of them have all configurable paramters available, and one of them does not have most of parameters.
```

For device with normal firmware user can adjust assist levels and many other things, you can see whole list in "Demo" mode
