### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by boopdadm** [andrey-pr/OpenBafangTool#7]
first, congrats @andrey-pr for this great project !!

I am having an issue at connection step:

![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/a7362692-f59a-4046-9dfd-a16b14d9cf9a)

But I can't find why :/

what I do:
1. download latest appimage (I am on fedora 40)
2. run
3. connect the cable to motor controler (green round shaped connector), turn on battery, plug the cable into the usb port
4. I select the following, and then I clicked check connection

![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/365001ab-bbe8-4287-966f-20d2f223affd)

6. upon first connection error, I applied this https://github.com/andrey-pr/OpenBafangTool#hid-troubleshooting-on-linux
7. still having connection error
8. I looked up VID/PID with lsusb:
```
Bus 001 Device 010: ID 1a86:7523 QinHeng Electronics CH340 serial converter
```
9. I replaced ATTRS{idVendor} and ATTRS{idProduct} in the following :

```
SUBSYSTEM=="input", GROUP="input", MODE="---rw-rw-rw-"
SUBSYSTEM=="usb", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", MODE:="rw-rw-rw-", GROUP="plugdev"
KERNEL=="hidraw*", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", MODE="---rw-rw-rw-", GROUP="plugdev"
```

10. ran again `sudo udevadm control --reload-rules`, unplugged replugged, but connection error persists. 
11. I also tried another usb port, same issue :(

do you have any idea why ? what can I do to troubleshoot this ?

**Comment by andrey-pr** [comment]
This troubleshooting manual is for HID devices (Besst Tool, that is for CAN bus motors). You use uart, search serial port troubleshooting manual right for your distributive. At first check with picocom or another serial port monitor, if /dev/ttyUSB available without sudo

**Comment by andrey-pr** [comment]
This troubleshooting manual is for HID devices (Besst Tool, that is for CAN bus motors). You use uart, search serial port troubleshooting manual right for your distributive. At first check with picocom or another serial port monitor, if /dev/ttyUSB available without sudo

**Comment by boopdadm** [comment]
ok. Adding my user to group dialout allows me to access /dev/ttyUSB0 without sudo.
so connection test is succeeding, I can select.

Then interface is loading for a while (~60s) 
![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/3656953c-bf4c-43d6-98c5-df43f984824b)

But values are mostly empty or wrong
![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/c6950523-5441-4308-9fc0-2d252c2e626a)

If clicking on refresh, the firmware value appears: CRR2093624E010022.3

When switching to parameters tab, most values are set to 0, and upon refresh it quickly says 
![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/6ef87391-b2b8-456d-87b7-343b43fecfa1)

any idea why ?

**Comment by andrey-pr** [comment]
> ok. Adding my user to group dialout allows me to access /dev/ttyUSB0 without sudo.
> so connection test is succeeding, I can select.
> 
> Then interface is loading for a while (~60s) 
> ![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/3656953c-bf4c-43d6-98c5-df43f984824b)
> 
> But values are mostly empty or wrong
> ![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/c6950523-5441-4308-9fc0-2d252c2e626a)
> 
> If clicking on refresh, the firmware value appears: CRR2093624E010022.3
> 
> When switching to parameters tab, most values are set to 0, and upon refresh it quickly says 
> ![image](https://github.com/andrey-pr/OpenBafangTool/assets/62545846/6ef87391-b2b8-456d-87b7-343b43fecfa1)
> 
> any idea why ?

Its not loading, but reading screen. 60s is timeout. Program can not read values from your device correctly. Are you sure that your serial port works correctly?

**Comment by boopdadm** [comment]
I assumed the following meant serial port was working correctly:
```
$ picocom /dev/ttyUSB0
picocom v3.1

port is        : /dev/ttyUSB0
flowcontrol    : none
baudrate is    : 9600
parity is      : none
databits are   : 8
stopbits are   : 1
escape is      : C-a
local echo is  : no
noinit is      : no
noreset is     : no
hangup is      : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv -E
imap is        : 
omap is        : 
emap is        : crcrlf,delbs,
logfile is     : none
initstring     : none
exit_after is  : not set
exit is        : no

Type [C-a] [C-h] to see available commands
Terminal ready


```

**Comment by boopdadm** [comment]
Closing here as connection error is solved. See here for values issues https://github.com/andrey-pr/OpenBafangTool/issues/9
